// Generated by Dagger (https://dagger.dev).
package com.evgtrush.toDoKa.presentation.todoka_lists;

import com.evgtrush.toDoKa.domain.interactors.ToDoKaListInteractor;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ToDoKaListsViewModel_Factory implements Factory<ToDoKaListsViewModel> {
  private final Provider<ToDoKaListInteractor> interactorProvider;

  public ToDoKaListsViewModel_Factory(Provider<ToDoKaListInteractor> interactorProvider) {
    this.interactorProvider = interactorProvider;
  }

  @Override
  public ToDoKaListsViewModel get() {
    return newInstance(interactorProvider.get());
  }

  public static ToDoKaListsViewModel_Factory create(
      Provider<ToDoKaListInteractor> interactorProvider) {
    return new ToDoKaListsViewModel_Factory(interactorProvider);
  }

  public static ToDoKaListsViewModel newInstance(ToDoKaListInteractor interactor) {
    return new ToDoKaListsViewModel(interactor);
  }
}
